// ============================================================================
// TWO STEPS VALLEY - POTWORY (ENEMIES)
// ============================================================================
// Plik ten definiuje wszystkie przeciwników gry.
// Każdy enemy ma:
//   - name: nazwa potwora (PL)
//   - emoji: ikonka do wyświetlania
//   - hp: punkty życia
//   - atk: siła ataku
//   - def: obrona
//   - xp: XP do zdobycia
//   - coins: monety do zdobycia
//   - level: wymagany poziom gracza
//   - tier: kategoria (easy, medium, hard, rare, legendary, boss)
//   - loot: przedmioty zdobyte po pokonaniu
//   - weakTo: do których typów obrażeń jest wrażliwy
// ============================================================================

module.exports = {
    // === ŁATWE (easy) ===
    wolf: {
        name: 'Wilk',
        emoji: '🐺',
        hp: 40,
        atk: 8,
        def: 3,
        xp: 15,
        coins: 20,
        level: 1,
        tier: 'easy',
        loot: 'smałowana_skoń',
        weakTo: ['fire', 'ice'],
    },
    spider: {
        name: 'Pająk',
        emoji: '🕷️',
        hp: 35,
        atk: 6,
        def: 2,
        xp: 12,
        coins: 15,
        level: 1,
        tier: 'easy',
        loot: 'pającze_jad',
        weakTo: ['fire'],
    },

    // === ŚREDNIE (medium) ===
    zombie: {
        name: 'Zombi',
        emoji: '🧟',
        hp: 120,
        atk: 18,
        def: 8,
        xp: 40,
        coins: 50,
        level: 3,
        tier: 'medium',
        loot: 'zombie_części',
        weakTo: ['fire'],
    },
    skeleton: {
        name: 'Szkielet',
        emoji: '💀',
        hp: 100,
        atk: 22,
        def: 6,
        xp: 35,
        coins: 45,
        level: 3,
        tier: 'medium',
        loot: 'kości',
        weakTo: ['holy'],
    },

    // === TRUDNE (hard) ===
    orc: {
        name: 'Ork Wojownik',
        emoji: '👹',
        hp: 350,
        atk: 45,
        def: 20,
        xp: 100,
        coins: 200,
        level: 5,
        tier: 'hard',
        loot: 'orkowe_bronie',
        weakTo: ['ice'],
    },
    golem: {
        name: 'Kamienny Golem',
        emoji: '🗿',
        hp: 800,
        atk: 35,
        def: 60,
        xp: 250,
        coins: 500,
        level: 5,
        tier: 'hard',
        loot: 'kamienny_pył',
        weakTo: ['acid'],
    },

    // === SZEROKIE (wide) ===
    slime: {
        name: 'Maślak',
        emoji: '💧',
        hp: 60,
        atk: 5,
        def: 1,
        xp: 10,
        coins: 10,
        level: 1,
        tier: 'wide',
        loot: 'maślak',
        weakTo: ['electric'],
    },

    rat: {
        name: 'Szczur',
        emoji: '🐀',
        hp: 25,
        atk: 3,
        def: 1,
        xp: 8,
        coins: 8,
        level: 1,
        tier: 'wide',
        loot: 'szczur',
        weakTo: ['poison'],
    },

    bug: {
        name: 'Chruścik',
        emoji: '🪲',
        hp: 20,
        atk: 2,
        def: 0,
        xp: 5,
        coins: 5,
        level: 1,
        tier: 'wide',
        loot: 'chruścik',
        weakTo: ['fire'],
    },

    bat: {
        name: 'Lotniak',
        emoji: '🦇',
        hp: 45,
        atk: 10,
        def: 4,
        xp: 18,
        coins: 18,
        level: 2,
        tier: 'wide',
        loot: 'krwią_lotniaka',
        weakTo: ['light'],
    },

    // === RZADKIE (rare) ===
    shadow: {
        name: 'Cieniostwór',
        emoji: '👻',
        hp: 500,
        atk: 55,
        def: 15,
        xp: 200,
        coins: 350,
        level: 7,
        tier: 'rare',
        loot: 'cieniowa_esencja',
        weakTo: ['light'],
    },
    necro: {
        name: 'Nekromanta',
        emoji: '🧙‍♂️',
        hp: 600,
        atk: 60,
        def: 25,
        xp: 250,
        coins: 400,
        level: 8,
        tier: 'rare',
        loot: 'księga_nekromancji',
        weakTo: ['holy'],
    },
    void_walker: {
        name: 'Spacerownik Pustki',
        emoji: '🌑',
        hp: 900,
        atk: 70,
        def: 30,
        xp: 350,
        coins: 550,
        level: 9,
        tier: 'rare',
        loot: 'pustkowa_płomień',
        weakTo: ['light'],
    },

    // === LEGENDARNE (legendary) ===
    dragon: {
        name: 'Smok',
        emoji: '🐉',
        hp: 1500,
        atk: 80,
        def: 50,
        xp: 800,
        coins: 1200,
        level: 10,
        tier: 'legendary',
        loot: 'skrzydła_smoka',
        weakTo: ['ice'],
    },
    phoenix: {
        name: 'Fenix',
        emoji: '🔥🐦',
        hp: 1800,
        atk: 75,
        def: 45,
        xp: 900,
        coins: 1400,
        level: 10,
        tier: 'legendary',
        loot: 'popiół_feniksa',
        weakTo: ['holy'],
    },
    ice_golem: {
        name: 'Lodowy Golem',
        emoji: '❄️🗿',
        hp: 2000,
        atk: 65,
        def: 70,
        xp: 1000,
        coins: 1500,
        level: 10,
        tier: 'legendary',
        loot: 'lód',
        weakTo: ['fire'],
    },
    lava_golem: {
        name: 'Lawowy Golem',
        emoji: '🌋🗿',
        hp: 2200,
        atk: 70,
        def: 65,
        xp: 1100,
        coins: 1600,
        level: 11,
        tier: 'legendary',
        loot: 'magma',
        weakTo: ['water'],
    },

    // === BOSSY (boss) ===
    wolf_king: {
        name: 'Król Wilków',
        emoji: '👑🐺',
        hp: 800,
        atk: 35,
        def: 20,
        xp: 500,
        coins: 800,
        level: 5,
        tier: 'boss',
        loot: 'legendarna_bron',
        weakTo: ['ice'],
        abilities: [
            { name: 'Zawrzenie', damage: 30, cooldown: 30 },
            { name: 'Zawrzenie', damage: 30, cooldown: 15 },
        ],
    },
    spider_mother: {
        name: 'Pajęcza Matka',
        emoji: '👑🕷️',
        hp: 1200,
        atk: 50,
        def: 40,
        xp: 800,
        coins: 1500,
        level: 8,
        tier: 'boss',
        loot: 'legendarna_zbroja',
        weakTo: ['fire'],
        abilities: [
            { name: 'Jad', damage: 40, cooldown: 20 },
            { name: 'Poczekalnia', damage: 50, cooldown: 30 },
            { name: 'Web', damage: 35, cooldown: 25 },
        ],
    },
    dragon_lord: {
        name: 'Władca Smoków',
        emoji: '👑🐉',
        hp: 3000,
        atk: 90,
        def: 60,
        xp: 1500,
        coins: 2500,
        level: 12,
        tier: 'boss',
        loot: 'legendarna_zbroja_smoka',
        weakTo: ['ice', 'holy'],
        abilities: [
            { name: 'Ognista Oddech', damage: 60, cooldown: 35 },
            { name: 'Skrzydła', damage: 50, cooldown: 25 },
            { name: 'Skok', damage: 45, cooldown: 30 },
        ],
    },
    void_emperor: {
        name: 'Czarodziej Pustki',
        emoji: '👑🌑',
        hp: 4000,
        atk: 100,
        def: 80,
        xp: 2000,
        coins: 3000,
        level: 15,
        tier: 'boss',
        loot: 'legendarna_bron_pustki',
        weakTo: ['light', 'holy'],
        abilities: [
            { name: 'Pustki', damage: 80, cooldown: 40 },
            { name: 'Cień', damage: 70, cooldown: 30 },
            { name: 'Absorb', damage: 60, cooldown: 35 },
        ],
    },
    crystal_god: {
        name: 'Bóg Kryształu',
        emoji: '👑💎',
        hp: 5000,
        atk: 110,
        def: 90,
        xp: 2500,
        coins: 4000,
        level: 20,
        tier: 'boss',
        loot: 'legendarna_zbroja_kryształu',
        weakTo: ['ice'],
        abilities: [
            { name: 'Kryształu', damage: 90, cooldown: 45 },
            { name: 'Oblak', damage: 85, cooldown: 35 },
            { name: 'Reflekcja', damage: 75, cooldown: 40 },
        ],
    },
};
