// ============================================================================
// TWO STEPS VALLEY - EKWIPUNEK (EQUIPMENT ITEMS)
// ============================================================================
// Plik ten definiuje wszystkie ekwipunki gry.
// Kategoria equipment ma:
//   - id: unikalne identyfikator
//   - name: nazwa przedmiotu (PL)
//   - emoji: ikonka do wyświetlania
//   - atk: siła ataku
//   - def: siła obrony
//   - hp: dodatkowe HP
//   - type: slot (weapon, helmet, chest, pants, boots, shield, ring)
//   - rarity: rzadkość (common, uncommon, rare, epic, legendary, mythic)
//   - requires: wymagania (poziom, poziom postaci)
//   - description: opis przedmiotu
// ============================================================================

module.exports = {
    // === STARTOWE EKWIPUNKI (Starter) ===
    starter: {
        weapon: {
            id: 'start_weap',
            name: 'Kostny kij',
            emoji: '🥢',
            atk: 5,
            def: 0,
            hp: 0,
            type: 'weapon',
            rarity: 'common',
            requires: { level: 1 },
            description: 'Początkowa broń z kostnych resztek.',
        },
        helmet: {
            id: 'start_helm',
            name: 'Kask skórny',
            emoji: '🪶',
            atk: 0,
            def: 3,
            hp: 10,
            type: 'helmet',
            rarity: 'common',
            requires: { level: 1 },
            description: 'Początkowy kask wykonany z skóry.',
        },
        chest: {
            id: 'start_chest',
            name: 'Kamizelka',
            emoji: '🦴',
            atk: 0,
            def: 5,
            hp: 15,
            type: 'chest',
            rarity: 'common',
            requires: { level: 1 },
            description: 'Początkowa kamizelka z kostnych resztek.',
        },
        pants: {
            id: 'start_pants',
            name: 'Szkoty',
            emoji: '🧦',
            atk: 0,
            def: 4,
            hp: 10,
            type: 'pants',
            rarity: 'common',
            requires: { level: 1 },
            description: 'Początkowe spodnie ze skóry.',
        },
        boots: {
            id: 'start_boots',
            name: 'Trzewiki',
            emoji: '👢',
            atk: 0,
            def: 3,
            hp: 5,
            type: 'boots',
            rarity: 'common',
            requires: { level: 1 },
            description: 'Początkowe trzewiki z miękkiej skóry.',
        },
        shield: {
            id: 'start_shield',
            name: 'Tarcza',
            emoji: '🛡️',
            atk: 0,
            def: 8,
            hp: 0,
            type: 'shield',
            rarity: 'common',
            requires: { level: 1 },
            description: 'Prosta tarcza z drewna.',
        },
        ring: {
            id: 'start_ring',
            name: 'Pierścień',
            emoji: '💍',
            atk: 0,
            def: 0,
            hp: 0,
            type: 'ring',
            rarity: 'common',
            requires: { level: 1 },
            description: 'Prosty pierścień bez właściwości.',
        },
    },

    // === PODSTAWOWE (Basic) ===
    basic: {
        weapon: {
            id: 'basic_weapon',
            name: 'Drewniana Bron',
            emoji: '🪵⚔️',
            atk: 12,
            def: 0,
            hp: 0,
            type: 'weapon',
            rarity: 'common',
            requires: { level: 3, miningLevel: 1 },
            description: 'Prosta broń z drewna.',
        },
        helmet: {
            id: 'basic_helm',
            name: 'Prosty Hełm',
            emoji: '🪖',
            atk: 0,
            def: 8,
            hp: 25,
            type: 'helmet',
            rarity: 'common',
            requires: { level: 3, miningLevel: 1 },
            description: 'Prosty hełm z metalu.',
        },
        chest: {
            id: 'basic_chest',
            name: 'Prosta Zbroja',
            emoji: '🧥',
            atk: 0,
            def: 15,
            hp: 50,
            type: 'chest',
            rarity: 'common',
            requires: { level: 3, miningLevel: 1 },
            description: 'Podstawowa zbroja z metalu.',
        },
        pants: {
            id: 'basic_pants',
            name: 'Proste Spodnie',
            emoji: '👖',
            atk: 0,
            def: 12,
            hp: 25,
            type: 'pants',
            rarity: 'common',
            requires: { level: 3, miningLevel: 1 },
            description: 'Proste spodnie z grubej tkanki.',
        },
        boots: {
            id: 'basic_boots',
            name: 'Proste Buty',
            emoji: '👢',
            atk: 0,
            def: 10,
            hp: 15,
            type: 'boots',
            rarity: 'common',
            requires: { level: 3, miningLevel: 1 },
            description: 'Proste buty z grubej skóry.',
        },
        shield: {
            id: 'basic_shield',
            name: 'Prosta Tarcza',
            emoji: '🛡️',
            atk: 0,
            def: 18,
            hp: 0,
            type: 'shield',
            rarity: 'common',
            requires: { level: 3, miningLevel: 1 },
            description: 'Podstawowa tarcza z metalu.',
        },
        ring: {
            id: 'basic_ring',
            name: 'Prosty Pierścień',
            emoji: '💍',
            atk: 0,
            def: 0,
            hp: 0,
            type: 'ring',
            rarity: 'common',
            requires: { level: 3, miningLevel: 1 },
            description: 'Prosty pierścień z metalu.',
        },
    },

    // === ZŁOTE (Gold) ===
    gold: {
        weapon: {
            id: 'gold_weapon',
            name: 'Złota Bron',
            emoji: '🗡️🟡',
            atk: 25,
            def: 0,
            hp: 0,
            type: 'weapon',
            rarity: 'epic',
            requires: { level: 8, miningLevel: 3 },
            description: 'Broń wykończona ze złota.',
        },
        helmet: {
            id: 'gold_helm',
            name: 'Hełm Złoty',
            emoji: '🪖🟡',
            atk: 0,
            def: 20,
            hp: 60,
            type: 'helmet',
            rarity: 'epic',
            requires: { level: 8, miningLevel: 3 },
            description: 'Hełm wykończony ze złota.',
        },
        chest: {
            id: 'gold_chest',
            name: 'Pancerz Złoty',
            emoji: '🧥🟡',
            atk: 0,
            def: 35,
            hp: 120,
            type: 'chest',
            rarity: 'epic',
            requires: { level: 8, miningLevel: 3 },
            description: 'Pancerz wykończony ze złota.',
        },
        pants: {
            id: 'gold_pants',
            name: 'Spodnie Złote',
            emoji: '👖🟡',
            atk: 0,
            def: 25,
            hp: 60,
            type: 'pants',
            rarity: 'epic',
            requires: { level: 8, miningLevel: 3 },
            description: 'Spodnie wykończone ze złota.',
        },
        boots: {
            id: 'gold_boots',
            name: 'Buty Złote',
            emoji: '👢🟡',
            atk: 0,
            def: 22,
            hp: 30,
            type: 'boots',
            rarity: 'epic',
            requires: { level: 8, miningLevel: 3 },
            description: 'Buty wykończone ze złota.',
        },
        shield: {
            id: 'gold_shield',
            name: 'Tarcza Złota',
            emoji: '🛡️🟡',
            atk: 0,
            def: 30,
            hp: 0,
            type: 'shield',
            rarity: 'epic',
            requires: { level: 8, miningLevel: 3 },
            description: 'Tarcza wykończona ze złota.',
        },
        ring: {
            id: 'gold_ring',
            name: 'Złoty Pierścień',
            emoji: '💍🟡',
            atk: 5,
            def: 0,
            hp: 0,
            type: 'ring',
            rarity: 'epic',
            requires: { level: 8, miningLevel: 3 },
            description: 'Pierścień wykończony ze złota.',
        },
    },

    // === EPICKIE (Epic) ===
    epic: {
        weapon: {
            id: 'epic_weapon',
            name: 'Miecz Epicki',
            emoji: '⚔️✨',
            atk: 45,
            def: 5,
            hp: 0,
            type: 'weapon',
            rarity: 'epic',
            requires: { level: 12, miningLevel: 4 },
            description: 'Miecz o epickiej sile.',
        },
        helmet: {
            id: 'epic_helm',
            name: 'Hełm Epicki',
            emoji: '🪖✨',
            atk: 0,
            def: 30,
            hp: 80,
            type: 'helmet',
            rarity: 'epic',
            requires: { level: 12, miningLevel: 4 },
            description: 'Hełm o epickiej sile.',
        },
        chest: {
            id: 'epic_chest',
            name: 'Pancerz Epicki',
            emoji: '🧥✨',
            atk: 0,
            def: 50,
            hp: 150,
            type: 'chest',
            rarity: 'epic',
            requires: { level: 12, miningLevel: 4 },
            description: 'Pancerz o epickiej sile.',
        },
        pants: {
            id: 'epic_pants',
            name: 'Spodnie Epickie',
            emoji: '👖✨',
            atk: 0,
            def: 35,
            hp: 80,
            type: 'pants',
            rarity: 'epic',
            requires: { level: 12, miningLevel: 4 },
            description: 'Spodnie o epickiej sile.',
        },
        boots: {
            id: 'epic_boots',
            name: 'Buty Epickie',
            emoji: '👢✨',
            atk: 0,
            def: 30,
            hp: 40,
            type: 'boots',
            rarity: 'epic',
            requires: { level: 12, miningLevel: 4 },
            description: 'Buty o epickiej sile.',
        },
        shield: {
            id: 'epic_shield',
            name: 'Tarcza Epicka',
            emoji: '🛡️✨',
            atk: 0,
            def: 45,
            hp: 0,
            type: 'shield',
            rarity: 'epic',
            requires: { level: 12, miningLevel: 4 },
            description: 'Tarcza o epickiej sile.',
        },
        ring: {
            id: 'epic_ring',
            name: 'Pierścień Epicki',
            emoji: '💍✨',
            atk: 10,
            def: 0,
            hp: 0,
            type: 'ring',
            rarity: 'epic',
            requires: { level: 12, miningLevel: 4 },
            description: 'Pierścień o epickiej sile.',
        },
    },

    // === LEGENDARNE (Legendary) ===
    legendary: {
        weapon: {
            id: 'legendary_weapon',
            name: 'Miecz Legendarny',
            emoji: '⚔️🔥',
            atk: 70,
            def: 10,
            hp: 0,
            type: 'weapon',
            rarity: 'legendary',
            requires: { level: 16, miningLevel: 6 },
            description: 'Miecz legendarnych rozmiarów.',
        },
        helmet: {
            id: 'legendary_helm',
            name: 'Hełm Legendarny',
            emoji: '🪖🔥',
            atk: 0,
            def: 45,
            hp: 120,
            type: 'helmet',
            rarity: 'legendary',
            requires: { level: 16, miningLevel: 6 },
            description: 'Hełm legendarnych rozmiarów.',
        },
        chest: {
            id: 'legendary_chest',
            name: 'Pancerz Legendarny',
            emoji: '🧥🔥',
            atk: 0,
            def: 70,
            hp: 200,
            type: 'chest',
            rarity: 'legendary',
            requires: { level: 16, miningLevel: 6 },
            description: 'Pancerz legendarnych rozmiarów.',
        },
        pants: {
            id: 'legendary_pants',
            name: 'Spodnie Legendarne',
            emoji: '👖🔥',
            atk: 0,
            def: 50,
            hp: 120,
            type: 'pants',
            rarity: 'legendary',
            requires: { level: 16, miningLevel: 6 },
            description: 'Spodnie legendarnych rozmiarów.',
        },
        boots: {
            id: 'legendary_boots',
            name: 'Buty Legendarne',
            emoji: '👢🔥',
            atk: 0,
            def: 45,
            hp: 60,
            type: 'boots',
            rarity: 'legendary',
            requires: { level: 16, miningLevel: 6 },
            description: 'Buty legendarnych rozmiarów.',
        },
        shield: {
            id: 'legendary_shield',
            name: 'Tarcza Legendarna',
            emoji: '🛡️🔥',
            atk: 0,
            def: 65,
            hp: 0,
            type: 'shield',
            rarity: 'legendary',
            requires: { level: 16, miningLevel: 6 },
            description: 'Tarcza legendarnych rozmiarów.',
        },
        ring: {
            id: 'legendary_ring',
            name: 'Pierścień Legendarny',
            emoji: '💍🔥',
            atk: 15,
            def: 0,
            hp: 0,
            type: 'ring',
            rarity: 'legendary',
            requires: { level: 16, miningLevel: 6 },
            description: 'Pierścień legendarnych rozmiarów.',
        },
    },

    // === MITYCZNE (Mythic) ===
    mythic: {
        weapon: {
            id: 'mythic_weapon',
            name: 'Miecz Mityczny',
            emoji: '⚔️💫',
            atk: 100,
            def: 15,
            hp: 0,
            type: 'weapon',
            rarity: 'mythic',
            requires: { level: 20, miningLevel: 7 },
            description: 'Miecz mitycznych rozmiarów.',
        },
        helmet: {
            id: 'mythic_helm',
            name: 'Hełm Mityczny',
            emoji: '🪖💫',
            atk: 0,
            def: 60,
            hp: 160,
            type: 'helmet',
            rarity: 'mythic',
            requires: { level: 20, miningLevel: 7 },
            description: 'Hełm mitycznych rozmiarów.',
        },
        chest: {
            id: 'mythic_chest',
            name: 'Pancerz Mityczny',
            emoji: '🧥💫',
            atk: 0,
            def: 90,
            hp: 280,
            type: 'chest',
            rarity: 'mythic',
            requires: { level: 20, miningLevel: 7 },
            description: 'Pancerz mitycznych rozmiarów.',
        },
        pants: {
            id: 'mythic_pants',
            name: 'Spodnie Mityczne',
            emoji: '👖💫',
            atk: 0,
            def: 65,
            hp: 160,
            type: 'pants',
            rarity: 'mythic',
            requires: { level: 20, miningLevel: 7 },
            description: 'Spodnie mitycznych rozmiarów.',
        },
        boots: {
            id: 'mythic_boots',
            name: 'Buty Mityczne',
            emoji: '👢💫',
            atk: 0,
            def: 60,
            hp: 80,
            type: 'boots',
            rarity: 'mythic',
            requires: { level: 20, miningLevel: 7 },
            description: 'Buty mitycznych rozmiarów.',
        },
        shield: {
            id: 'mythic_shield',
            name: 'Tarcza Mityczna',
            emoji: '🛡️💫',
            atk: 0,
            def: 85,
            hp: 0,
            type: 'shield',
            rarity: 'mythic',
            requires: { level: 20, miningLevel: 7 },
            description: 'Tarcza mitycznych rozmiarów.',
        },
        ring: {
            id: 'mythic_ring',
            name: 'Pierścień Mityczny',
            emoji: '💍💫',
            atk: 20,
            def: 0,
            hp: 0,
            type: 'ring',
            rarity: 'mythic',
            requires: { level: 20, miningLevel: 7 },
            description: 'Pierścień mitycznych rozmiarów.',
        },
    },

    // === BOSOWSKIE (Boss Loot) ===
    boss_loot: {
        wolf_king: {
            name: 'Zęby Króla Wilków',
            emoji: '🦷',
            atk: 25,
            def: 0,
            hp: 0,
            type: 'weapon',
            rarity: 'legendary',
            dropFrom: 'wolf_king',
            description: 'Zęby pokonanego Króla Wilków.',
        },
        spider_mother: {
            name: 'Pajęcza Pancerz',
            emoji: '🕸️',
            atk: 0,
            def: 25,
            hp: 50,
            type: 'helmet',
            rarity: 'legendary',
            dropFrom: 'spider_mother',
            description: 'Pancerz z pajęczych pajęczych pajęczych pajęczy.',
        },
        dragon_lord: {
            name: 'Kłów Władcy Smoków',
            emoji: '🐉',
            atk: 45,
            def: 10,
            hp: 0,
            type: 'weapon',
            rarity: 'legendary',
            dropFrom: 'dragon_lord',
            description: 'Kłów pokonanego Władcy Smoków.',
        },
        void_emperor: {
            name: 'Miecz Pustki',
            emoji: '🌑',
            atk: 50,
            def: 5,
            hp: 0,
            type: 'weapon',
            rarity: 'legendary',
            dropFrom: 'void_emperor',
            description: 'Miecz z cienia pustki.',
        },
        crystal_god: {
            name: 'Kryształowy Miecz',
            emoji: '💎',
            atk: 55,
            def: 12,
            hp: 0,
            type: 'weapon',
            rarity: 'legendary',
            dropFrom: 'crystal_god',
            description: 'Miecz wykonany z kryształu.',
        },
        mythic_dragon: {
            name: 'Mityczny Ogon',
            emoji: '🐉',
            atk: 80,
            def: 20,
            hp: 0,
            type: 'weapon',
            rarity: 'mythic',
            dropFrom: 'mythic_dragon',
            description: 'Ogon mitycznego smoka.',
        },
    },
};
