// ============================================================================
// TWO STEPS VALLEY - SKLEP (SHOP ITEMS)
// ============================================================================
// Plik ten definiuje wszystkie przedmioty dostępne w sklepie.
// Każdy item ma:
//   - id: unikalne identyfikator
//   - name: nazwa przedmiotu (PL)
//   - emoji: ikonka do wyświetlania
//   - price: cena przedmiotu
//   - type: typ przedmiotu (potion, food, equipment, material, etc.)
//   - effect: efekt przedmiotu (atk, def, heal, mana, etc.)
//   - category: kategoria przedmiotu
//   - rarity: rzadkość
//   - description: opis przedmiotu
//   - slot: slot jeśli to ekwipunek
//   - value: wartość monet
//   - xpValue: wartość XP
// ============================================================================

module.exports = {
    // === MIKSTURY (Potions) ===
    potions: {
        'potion_strength': {
            id: 'potion_strength',
            name: 'Mikstura Siły',
            emoji: '🧪',
            price: 50,
            type: 'potion',
            effect: 'atk',
            effectValue: 5,
            category: 'potion',
            rarity: 'common',
            description: 'Zwiększa siłę ataku o 5.',
            consume: true,
        },
        'potion_luck': {
            id: 'potion_luck',
            name: 'Mikstura Szczęścia',
            emoji: '🔮',
            price: 80,
            type: 'potion',
            effect: 'luck',
            effectValue: 10,
            category: 'potion',
            rarity: 'common',
            description: 'Zwiększa szczęście o 10.',
            consume: true,
        },
        'potion_heal': {
            id: 'potion_heal',
            name: 'Mikstura Życia',
            emoji: '💉',
            price: 40,
            type: 'potion',
            effect: 'heal',
            effectValue: 50,
            category: 'potion',
            rarity: 'common',
            description: 'Wylecza 50 punktów życia.',
            consume: true,
        },
        'potion_rarity': {
            id: 'potion_rarity',
            name: 'Mikstura Rzadkości',
            emoji: '✨',
            price: 120,
            type: 'potion',
            effect: 'luck',
            effectValue: 20,
            category: 'potion',
            rarity: 'uncommon',
            description: 'Zwiększa szczęście o 20.',
            consume: true,
        },
        'legendary_potion': {
            id: 'legendary_potion',
            name: 'Legendarna Mikstura',
            emoji: '💫',
            price: 500,
            type: 'potion',
            effect: 'stat_boost',
            effectValue: 50,
            category: 'potion',
            rarity: 'legendary',
            description: 'Legendarne mikstura zwiększająca wszystkie statystyki.',
            consume: true,
        },
    },

    // === JEDZENIE (Food) ===
    food: {
        'bread': {
            id: 'bread',
            name: 'Chleb',
            emoji: '🍞',
            price: 20,
            type: 'food',
            effect: 'mana',
            effectValue: 30,
            category: 'food',
            rarity: 'common',
            description: 'Odrestruje 30 punktów maną.',
            consume: true,
        },
        'apple': {
            id: 'apple',
            name: 'Jabłko',
            emoji: '🍎',
            price: 10,
            type: 'food',
            effect: 'mana',
            effectValue: 20,
            category: 'food',
            rarity: 'common',
            description: 'Odrestruje 20 punktów maną.',
            consume: true,
        },
        'steak': {
            id: 'steak',
            name: 'Stek',
            emoji: '🥩',
            price: 150,
            type: 'food',
            effect: 'hp',
            effectValue: 100,
            category: 'food',
            rarity: 'common',
            description: 'Wylecza 100 punktów życia.',
            consume: true,
        },
        'soup': {
            id: 'soup',
            name: 'Zupa',
            emoji: '🍲',
            price: 60,
            type: 'food',
            effect: 'hp',
            effectValue: 60,
            category: 'food',
            rarity: 'common',
            description: 'Wylecza 60 punktów życia.',
            consume: true,
        },
        'pizza': {
            id: 'pizza',
            name: 'Pizze',
            emoji: '🍕',
            price: 100,
            type: 'food',
            effect: 'both',
            effectValue: { hp: 50, mana: 30 },
            category: 'food',
            rarity: 'common',
            description: 'Wylecza 50 HP i 30 Mana.',
            consume: true,
        },
        'salmon': {
            id: 'salmon',
            name: 'Salmonek',
            emoji: '🐟',
            price: 80,
            type: 'food',
            effect: 'both',
            effectValue: { hp: 70, mana: 40 },
            category: 'food',
            rarity: 'uncommon',
            description: 'Wylecza 70 HP i 40 Mana.',
            consume: true,
        },
    },

    // === MATERIAŁY (Materials) ===
    materials: {
        'wood': {
            id: 'wood_material',
            name: 'Drewno',
            emoji: '🌲',
            price: 15,
            type: 'material',
            category: 'wood',
            rarity: 'common',
            description: 'Drewno do tworzenia.',
        },
        'stone': {
            id: 'stone_material',
            name: 'Kamień',
            emoji: '🪨',
            price: 10,
            type: 'material',
            category: 'stone',
            rarity: 'common',
            description: 'Kamień do tworzenia.',
        },
        'coal': {
            id: 'coal_material',
            name: 'Węgiel',
            emoji: '⚫',
            price: 30,
            type: 'material',
            category: 'coal',
            rarity: 'common',
            description: 'Węgiel do tworzenia.',
        },
        'iron': {
            id: 'iron_material',
            name: 'Żelazo',
            emoji: '⛓️',
            price: 50,
            type: 'material',
            category: 'iron',
            rarity: 'common',
            description: 'Żelazo do tworzenia.',
        },
        'gold': {
            id: 'gold_material',
            name: 'Złoto',
            emoji: '🟡',
            price: 100,
            type: 'material',
            category: 'gold',
            rarity: 'common',
            description: 'Złoto do tworzenia.',
        },
        'diamond': {
            id: 'diamond_material',
            name: 'Diament',
            emoji: '💎',
            price: 300,
            type: 'material',
            category: 'diamond',
            rarity: 'rare',
            description: 'Diament do tworzenia.',
        },
        'ruby': {
            id: 'ruby_material',
            name: 'Rubin',
            emoji: '🔴',
            price: 500,
            type: 'material',
            category: 'ruby',
            rarity: 'rare',
            description: 'Rubin do tworzenia.',
        },
        'sapphire': {
            id: 'sapphire_material',
            name: 'Szafir',
            emoji: '🔷',
            price: 400,
            type: 'material',
            category: 'sapphire',
            rarity: 'rare',
            description: 'Szafir do tworzenia.',
        },
    },

    // === EKWIPUNEK (Equipment) ===
    equipment: {
        'beginner_sword': {
            id: 'beginner_sword',
            name: 'Kostny Kij',
            emoji: '🥢',
            price: 20,
            type: 'weapon',
            slot: 'weapon',
            atk: 5,
            def: 0,
            hp: 0,
            category: 'equipment',
            rarity: 'common',
            description: 'Początkowy kij z kostnych resztek.',
        },
        'iron_helm': {
            id: 'iron_helm',
            name: 'Prosty Hełm',
            emoji: '🪖',
            price: 300,
            type: 'helmet',
            slot: 'helmet',
            atk: 0,
            def: 8,
            hp: 25,
            category: 'equipment',
            rarity: 'common',
            description: 'Prosty hełm z metalu.',
        },
        'iron_chest': {
            id: 'iron_chest',
            name: 'Prosta Zbroja',
            emoji: '🧥',
            price: 500,
            type: 'chest',
            slot: 'chest',
            atk: 0,
            def: 15,
            hp: 50,
            category: 'equipment',
            rarity: 'common',
            description: 'Prosta zbroja z metalu.',
        },
        'iron_pants': {
            id: 'iron_pants',
            name: 'Proste Spodnie',
            emoji: '👖',
            price: 350,
            type: 'pants',
            slot: 'pants',
            atk: 0,
            def: 12,
            hp: 25,
            category: 'equipment',
            rarity: 'common',
            description: 'Proste spodnie z metalu.',
        },
        'iron_boots': {
            id: 'iron_boots',
            name: 'Proste Buty',
            emoji: '👢',
            price: 300,
            type: 'boots',
            slot: 'boots',
            atk: 0,
            def: 10,
            hp: 15,
            category: 'equipment',
            rarity: 'common',
            description: 'Proste buty z metalu.',
        },
        'iron_shield': {
            id: 'iron_shield',
            name: 'Prosta Tarcza',
            emoji: '🛡️',
            price: 400,
            type: 'shield',
            slot: 'shield',
            atk: 0,
            def: 18,
            hp: 0,
            category: 'equipment',
            rarity: 'common',
            description: 'Prosta tarcza z metalu.',
        },
        'iron_ring': {
            id: 'iron_ring',
            name: 'Prosty Pierścień',
            emoji: '💍',
            price: 250,
            type: 'ring',
            slot: 'ring',
            atk: 0,
            def: 0,
            hp: 0,
            category: 'equipment',
            rarity: 'common',
            description: 'Prosty pierścień z metalu.',
        },
    },

    // === KOSMETYKI (Cosmetics) ===
    cosmetics: {
        'bandana': {
            id: 'bandana',
            name: 'Bandana',
            emoji: '🧣',
            price: 100,
            type: 'cosmetic',
            category: 'cosmetic',
            rarity: 'common',
            description: 'Podstawowy bandana na twarz.',
        },
        'hat': {
            id: 'hat',
            name: 'Kapelusz',
            emoji: '🎩',
            price: 200,
            type: 'cosmetic',
            category: 'cosmetic',
            rarity: 'uncommon',
            description: 'Podstawowy kapelusz.',
        },
        'sword_skin': {
            id: 'sword_skin',
            name: 'Skórze Miecza',
            emoji: '⚔️🎨',
            price: 500,
            type: 'cosmetic',
            category: 'cosmetic',
            rarity: 'rare',
            description: 'Skóra na miecz.',
        },
        'sword_skin_fire': {
            id: 'sword_skin_fire',
            name: 'Ognisty Miecz',
            emoji: '⚔️🔥',
            price: 1500,
            type: 'cosmetic',
            category: 'cosmetic',
            rarity: 'epic',
            description: 'Ognista skóra na miecz.',
        },
        'sword_skin_water': {
            id: 'sword_skin_water',
            name: 'Wodny Miecz',
            emoji: '⚔️💧',
            price: 1500,
            type: 'cosmetic',
            category: 'cosmetic',
            rarity: 'epic',
            description: 'Wodna skóra na miecz.',
        },
        'sword_skin_nature': {
            id: 'sword_skin_nature',
            name: 'Drzewny Miecz',
            emoji: '⚔️🌿',
            price: 1500,
            type: 'cosmetic',
            category: 'cosmetic',
            rarity: 'epic',
            description: 'Drzewna skóra na miecz.',
        },
        'sword_skin_shadow': {
            id: 'sword_skin_shadow',
            name: 'Cień Miecza',
            emoji: '⚔️🌑',
            price: 2500,
            type: 'cosmetic',
            category: 'cosmetic',
            rarity: 'legendary',
            description: 'Skóra cienia na miecz.',
        },
    },

    // === NARZĘDZIA (Tools) ===
    tools: {
        'pickaxe': {
            id: 'pickaxe',
            name: 'Kopać',
            emoji: '⛏️',
            price: 50,
            type: 'tool',
            category: 'tool',
            rarity: 'common',
            description: 'Podstawowy kopać.',
        },
        'axe': {
            id: 'axe',
            name: 'Topór',
            emoji: '🪓',
            price: 100,
            type: 'tool',
            category: 'tool',
            rarity: 'common',
            description: 'Podstawowy topór.',
        },
        'fishing_rod': {
            id: 'fishing_rod',
            name: 'Rybactwo',
            emoji: '🎣',
            price: 150,
            type: 'tool',
            category: 'tool',
            rarity: 'common',
            description: 'Podstawowa rybackie sztuki.',
        },
        'bow': {
            id: 'bow',
            name: 'Łuk',
            emoji: '🏹',
            price: 300,
            type: 'tool',
            category: 'tool',
            rarity: 'uncommon',
            description: 'Podstawowy łuk.',
        },
    },

    // === KOSZTOWNIKI (Services) ===
    services: {
        'heal': {
            id: 'heal',
            name: 'Wyleczenie',
            emoji: '🏥',
            price: 50,
            type: 'service',
            category: 'service',
            rarity: 'common',
            description: 'Wylecza wszystkie HP.',
        },
        'craft': {
            id: 'craft',
            name: 'Zlecenie',
            emoji: '🔨',
            price: 200,
            type: 'service',
            category: 'service',
            rarity: 'common',
            description: 'Zlecenie przedmiotów.',
        },
    },
};
