// ============================================================================
// TWO STEPS VALLEY - PRACOWNIA (WORKERS)
// ============================================================================
// Pliki ten definiuje dostępne prace dla graczy.
// Każdy job ma:
//   - slot: slot gdzie gracz może pracować (lesnictwo, kopalnia, rolnictwo, etc.)
//   - cost: cena uruchomienia pracy
//   - duration: czas trwania pracy
//   - profitPerSec: zysk na sekundę (typ, ilość)
//   - requirements: wymagania (poziomy umiejętności)
// ============================================================================

module.exports = {
    // 🪵 Lesnictwo (Woodcutting)
    'woodcutting': {
        id: 'woodcutting',
        name: '🪓 Lesniczy',
        emoji: '🪓',
        cost: 50,
        duration: 30,
        profitPerSec: { wood: 0.5 },
        description: 'Karczowanie drzew dla drewna',
        requirements: { miningLevel: 1 },
        slot: 'lesnictwo',
    },
    'advanced_woodcutting': {
        id: 'advanced_woodcutting',
        name: '🌲 Ślusarz',
        emoji: '🔧',
        cost: 200,
        duration: 60,
        profitPerSec: { wood: 1.0 },
        description: 'Podeszlejsza obróbka drewna',
        requirements: { miningLevel: 2 },
        slot: 'rzemieślnictwo',
    },
    'master_woodcutting': {
        id: 'master_woodcutting',
        name: '🌲🪵 Mistrz Drewna',
        emoji: '🌲',
        cost: 500,
        duration: 120,
        profitPerSec: { wood: 2.0 },
        description: 'Ekspercka praca z drewnem',
        requirements: { miningLevel: 3 },
        slot: 'lesnictwo',
    },

    // 🪨 Kopalnia (Mining)
    'mining': {
        id: 'mining',
        name: '⛏️ Kopalnik',
        emoji: '⛏️',
        cost: 100,
        duration: 45,
        profitPerSec: { stone: 0.8 },
        description: 'Kopanie kamienia w kopalni',
        requirements: { miningLevel: 1 },
        slot: 'kopalnia',
    },
    'deep_mining': {
        id: 'deep_mining',
        name: '🪨 Głęboki Kopalnik',
        emoji: '🔩',
        cost: 300,
        duration: 90,
        profitPerSec: { stone: 1.5, coal: 0.3 },
        description: 'Kopanie w głębokich kopalniach',
        requirements: { miningLevel: 3 },
        slot: 'kopalnia',
    },
    'master_mining': {
        id: 'master_mining',
        name: '💎 Mistrz Górnik',
        emoji: '💎',
        cost: 800,
        duration: 180,
        profitPerSec: { coal: 0.8, iron: 0.4, gold: 0.2 },
        description: 'Eksperckie kopanie cennych surowców',
        requirements: { miningLevel: 5 },
        slot: 'kopalnia',
    },

    // 🌾 Rolnictwo (Farming)
    'farming': {
        id: 'farming',
        name: '🌱 Rolnik',
        emoji: '🌾',
        cost: 75,
        duration: 40,
        profitPerSec: { wheat: 0.6, carrots: 0.4 },
        description: 'Uprawianie plonów na farmie',
        requirements: { farmingLevel: 1 },
        slot: 'rolnictwo',
    },
    'greenhouse_farming': {
        id: 'greenhouse_farming',
        name: '🏠 Hodowca Roślin',
        emoji: '🌻',
        cost: 250,
        duration: 80,
        profitPerSec: { wheat: 1.2, carrots: 0.8, pumpkins: 0.5 },
        description: 'Uprawianie w szklarni',
        requirements: { farmingLevel: 3 },
        slot: 'rolnictwo',
    },
    'master_farming': {
        id: 'master_farming',
        name: '🌾 Mistrz Rolnik',
        emoji: '🌿',
        cost: 700,
        duration: 160,
        profitPerSec: { wheat: 2.0, carrots: 1.5, pumpkins: 1.0, berries: 0.8 },
        description: 'Zaawansowane uprawy rolnicze',
        requirements: { farmingLevel: 5 },
        slot: 'rolnictwo',
    },

    // 🎣 Rybołówstwo (Fishing)
    'fishing': {
        id: 'fishing',
        name: '🎣 Rybak',
        emoji: '🎣',
        cost: 60,
        duration: 35,
        profitPerSec: { trout: 0.4, bass: 0.3 },
        description: 'Rybackie sztuki na stawie',
        requirements: { fishingLevel: 1 },
        slot: 'rybackie',
    },
    'deep_sea_fishing': {
        id: 'deep_sea_fishing',
        name: '⚓ Rybak Wysokiej Morza',
        emoji: '🐙',
        cost: 300,
        duration: 85,
        profitPerSec: { salmon: 0.9, tuna: 0.7, shark: 0.3 },
        description: 'Rybackie sztuki na głębokim morzu',
        requirements: { fishingLevel: 4 },
        slot: 'rybackie',
    },
    'master_fishing': {
        id: 'master_fishing',
        name: '🐋 Mistrz Rybak',
        emoji: '🐋',
        cost: 900,
        duration: 200,
        profitPerSec: { tuna: 1.5, shark: 0.8, whale: 0.5, legendary_fish: 0.1 },
        description: 'Eksperckie rybackie sztuki',
        requirements: { fishingLevel: 7 },
        slot: 'rybackie',
    },

    // 🔨 Rzemieślnictwo (Crafting)
    'basic_crafting': {
        id: 'basic_crafting',
        name: '🔨 Rzemieślnik',
        emoji: '🔨',
        cost: 150,
        duration: 60,
        profitPerSec: { iron: 0.3, wood: 0.6 },
        description: 'Tworzenie przedmiotów z surowców',
        requirements: { miningLevel: 2 },
        slot: 'rzemieślnictwo',
    },
    'advanced_crafting': {
        id: 'advanced_crafting',
        name: '🛡️ Mistrz Rzemieślnik',
        emoji: '🛡️',
        cost: 450,
        duration: 120,
        profitPerSec: { iron: 0.8, wood: 1.2, gold: 0.2 },
        description: 'Zaawansowana obróbka surowców',
        requirements: { miningLevel: 4 },
        slot: 'rzemieślnictwo',
    },
    'master_crafting': {
        id: 'master_crafting',
        name: '⚔️ Legendarne Rzemieślnictwo',
        emoji: '⚔️',
        cost: 1000,
        duration: 240,
        profitPerSec: { diamond: 0.5, ruby: 0.3, legendary_item: 0.2 },
        description: 'Tworzenie legendarnych przedmiotów',
        requirements: { miningLevel: 6 },
        slot: 'rzemieślnictwo',
    },

    // 🧪 Alchemia (Alchemy)
    'basic_alchemy': {
        id: 'basic_alchemy',
        name: '🧪 Alchemik',
        emoji: '🧪',
        cost: 200,
        duration: 70,
        profitPerSec: { potion_strength: 0.2, potion_heal: 0.3 },
        description: 'Tworzenie prostych mikstur',
        requirements: { farmingLevel: 2 },
        slot: 'alchemia',
    },
    'master_alchemy': {
        id: 'master_alchemy',
        name: '🔮 Wielki Alchemik',
        emoji: '🔮',
        cost: 600,
        duration: 140,
        profitPerSec: { potion_luck: 0.3, potion_rarity: 0.15 },
        description: 'Tworzenie rzadkich mikstur',
        requirements: { farmingLevel: 4 },
        slot: 'alchemia',
    },
    'legendary_alchemy': {
        id: 'legendary_alchemy',
        name: '✨ Mistrz Alchemik',
        emoji: '✨',
        cost: 1200,
        duration: 280,
        profitPerSec: { legendary_potion: 0.25 },
        description: 'Tworzenie legendarnych mikstur',
        requirements: { farmingLevel: 7 },
        slot: 'alchemia',
    },

    // 🏺 Archeologia (Excavation)
    'excavation': {
        id: 'excavation',
        name: '🏺 Archeolog',
        emoji: '🏺',
        cost: 180,
        duration: 75,
        profitPerSec: { stone: 0.5, artifact: 0.1 },
        description: 'Wykopywanie ruín i zabytków',
        requirements: { miningLevel: 2 },
        slot: 'archeologia',
    },
    'master_excavation': {
        id: 'master_excavation',
        name: '🏛️ Mistrz Archeolog',
        emoji: '🏛️',
        cost: 600,
        duration: 150,
        profitPerSec: { artifact: 0.3, rare_artifact: 0.08 },
        description: 'Wykopywanie rzadkich zabytków',
        requirements: { miningLevel: 5 },
        slot: 'archeologia',
    },
    'legendary_excavation': {
        id: 'legendary_excavation',
        name: '👑 Legendarne Ruiny',
        emoji: '👑',
        cost: 1500,
        duration: 300,
        profitPerSec: { legendary_artifact: 0.2 },
        description: 'Wykopywanie legendarnych zabytków',
        requirements: { miningLevel: 7 },
        slot: 'archeologia',
    },
};
