// ============================================================
//   KONFIGURACJA RYB – Zbalansowana i rozszerzona
// ============================================================

const FISH = {
    // ── POSPOLITE (common) – Suma: 55% ──────────────────────
    karp: {
        name: "Karp",
        emoji: "🐟",
        rarity: "common",
        chance: 15,
        minWeight: 0.5,
        maxWeight: 8.0,
        baseValue: 10,
        xp: 5,
    },
    ploc: {
        name: "Płoć",
        emoji: "🐠",
        rarity: "common",
        chance: 12,
        minWeight: 0.1,
        maxWeight: 1.5,
        baseValue: 8,
        xp: 4,
    },
    leszcz: {
        name: "Leszcz",
        emoji: "🐡",
        rarity: "common",
        chance: 10,
        minWeight: 0.3,
        maxWeight: 4.0,
        baseValue: 12,
        xp: 5,
    },
    karas: {
        name: "Karaś",
        emoji: "🐟",
        rarity: "common",
        chance: 10,
        minWeight: 0.1,
        maxWeight: 1.2,
        baseValue: 6,
        xp: 3,
    },
    ukleja: {
        name: "Ukleja",
        emoji: "🐟",
        rarity: "common",
        chance: 8,
        minWeight: 0.01,
        maxWeight: 0.15,
        baseValue: 3,
        xp: 2,
    },

    // ── NIEPOSPOLITE (uncommon) – Suma: 25% ─────────────────
    szczupak: {
        name: "Szczupak",
        emoji: "🦈",
        rarity: "uncommon",
        chance: 8,
        minWeight: 1.0,
        maxWeight: 15.0,
        baseValue: 40,
        xp: 15,
    },
    okon: {
        name: "Okoń",
        emoji: "🐟",
        rarity: "uncommon",
        chance: 7,
        minWeight: 0.2,
        maxWeight: 3.0,
        baseValue: 30,
        xp: 12,
    },
    sandacz: {
        name: "Sandacz",
        emoji: "🐡",
        rarity: "uncommon",
        chance: 5,
        minWeight: 1.0,
        maxWeight: 12.0,
        baseValue: 55,
        xp: 25,
    },
    amur: {
        name: "Amur",
        emoji: "🐟",
        rarity: "uncommon",
        chance: 5,
        minWeight: 2.0,
        maxWeight: 25.0,
        baseValue: 45,
        xp: 20,
    },

    // ── RZADKIE (rare) – Suma: 13.5% ────────────────────────
    sum: {
        name: "Sum",
        emoji: "🐬",
        rarity: "rare",
        chance: 5,
        minWeight: 5.0,
        maxWeight: 60.0,
        baseValue: 100,
        xp: 40,
    },
    pstrag: {
        name: "Pstrąg",
        emoji: "🐟",
        rarity: "rare",
        chance: 4,
        minWeight: 0.5,
        maxWeight: 5.0,
        baseValue: 120,
        xp: 45,
    },
    wegorz: {
        name: "Węgorz",
        emoji: "🐍",
        rarity: "rare",
        chance: 2.5,
        minWeight: 0.5,
        maxWeight: 4.5,
        baseValue: 180,
        xp: 70,
    },
    belona: {
        name: "Belona",
        emoji: "🗡️",
        rarity: "rare",
        chance: 2,
        minWeight: 0.4,
        maxWeight: 2.0,
        baseValue: 150,
        xp: 65,
    },

    // ── EPICKIE (epic) – Suma: 5.4% ─────────────────────────
    losos: {
        name: "Łosoś",
        emoji: "🐡",
        rarity: "epic",
        chance: 3,
        minWeight: 3.0,
        maxWeight: 20.0,
        baseValue: 350,
        xp: 100,
    },
    jesiotr: {
        name: "Jesiotr",
        emoji: "🐋",
        rarity: "epic",
        chance: 1.5,
        minWeight: 10.0,
        maxWeight: 100.0,
        baseValue: 800,
        xp: 200,
    },
    marlin: {
        name: "Marlin Niebieski",
        emoji: "🗡️",
        rarity: "epic",
        chance: 0.5,
        minWeight: 50.0,
        maxWeight: 450.0,
        baseValue: 1400,
        xp: 350,
    },
    tunczyk: {
        name: "Tuńczyk",
        emoji: "🐟",
        rarity: "epic",
        chance: 0.4,
        minWeight: 30.0,
        maxWeight: 650.0,
        baseValue: 1800,
        xp: 450,
    },

    // ── LEGENDARNE (legendary) – Suma: 1.1% ─────────────────
    zlota_rybka: {
        name: "Złota Rybka",
        emoji: "✨🐠",
        rarity: "legendary",
        chance: 0.7,
        minWeight: 0.01,
        maxWeight: 0.1,
        baseValue: 5000,
        xp: 500,
    },
    smok_wodny: {
        name: "Smok Wodny",
        emoji: "🐉",
        rarity: "legendary",
        chance: 0.2,
        minWeight: 100.0,
        maxWeight: 500.0,
        baseValue: 20000,
        xp: 1500,
    },
    kraken: {
        name: "Młody Kraken",
        emoji: "🦑",
        rarity: "legendary",
        chance: 0.15,
        minWeight: 500.0,
        maxWeight: 2500.0,
        baseValue: 60000,
        xp: 5000,
    },
    lewiatan: {
        name: "Lewiatan",
        emoji: "🌊",
        rarity: "legendary",
        chance: 0.05,
        minWeight: 5000.0,
        maxWeight: 20000.0,
        baseValue: 250000,
        xp: 20000,
    },

    // ── ŚMIECI (trash) – Szansa sterowana przez TRASH_CHANCE ─
    but: {
        name: "Stary But", emoji: "👟", rarity: "trash", chance: 0,
        minWeight: 0.1, maxWeight: 0.5, baseValue: 0, xp: 1,
    },
    opona: {
        name: "Opona", emoji: "⭕", rarity: "trash", chance: 0,
        minWeight: 2.0, maxWeight: 8.0, baseValue: 0, xp: 1,
    },
    puszka: {
        name: "Puszka", emoji: "🥫", rarity: "trash", chance: 0,
        minWeight: 0.05, maxWeight: 0.1, baseValue: 0, xp: 1,
    },
    kotwica: {
        name: "Kotwica", emoji: "⚓", rarity: "trash", chance: 0,
        minWeight: 15.0, maxWeight: 40.0, baseValue: 15, xp: 10,
    },
};

const RARITY_STYLES = {
    trash:     { label: "Śmieci",       color: 0x808080, emoji: "🗑️" },
    common:    { label: "Pospolita",    color: 0x95a5a6, emoji: "⚪" },
    uncommon:  { label: "Niepospolita", color: 0x2ecc71, emoji: "🟢" },
    rare:      { label: "Rzadka",       color: 0x3498db, emoji: "🔵" },
    epic:      { label: "Epicka",       color: 0x9b59b6, emoji: "🟣" },
    legendary: { label: "Legendarna",   color: 0xf1c40f, emoji: "🌟" },
};

const FISHING_COOLDOWN = 30;
const TRASH_CHANCE = 8; // Lekko zwiększona szansa na śmieci

module.exports = { FISH, RARITY_STYLES, FISHING_COOLDOWN, TRASH_CHANCE };