-- Dodanie brakujących kolumn do tabeli profiles
-- Musi zostać uruchomione przez SQL editor w Supabase

ALTER TABLE profiles ADD COLUMN IF NOT EXISTS rank TEXT DEFAULT 'Novice';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS pln_balance DECIMAL(10,2) DEFAULT 0.00;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS weekly_xp INTEGER DEFAULT 0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS badges_unlocked INTEGER DEFAULT 0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS settings JSONB DEFAULT '{}';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS joined_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS discord_id TEXT UNIQUE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS discord_roles TEXT[] DEFAULT '{}'::text[];
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS fishing_gear JSONB DEFAULT '{}'::jsonb;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS background TEXT DEFAULT 'default';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS last_work TIMESTAMP WITH TIME ZONE;
