import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase-server";
import { checkProjectPermission, checkProjectMembership, logActivity } from "@/lib/dev-permissions";

export async function GET(request: Request) {
  let supabase;
  try {
    supabase = await createClient();
  } catch {
    return NextResponse.json(
      { error: "Dev tasks disabled - contact administrator" },
      { status: 503 }
    );
  }

  const { searchParams } = new URL(request.url);
  const projectId = searchParams.get("projectId");

  if (!projectId) {
    return NextResponse.json({ error: "Project ID is required" }, { status: 400 });
  }

  // Check if user has access to the project
  const membershipCheck = await checkProjectMembership(Number(projectId));
  if (!membershipCheck.hasAccess) {
    return NextResponse.json({ error: membershipCheck.error }, { status: 403 });
  }

  let query = supabase
    .from("dev_tasks")
    .select("*")
    .order("created_at", { ascending: false });

  if (projectId) {
    query = query.eq("project_id", Number(projectId));
  }

  const { data, error } = await query;

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  // Return empty array if no tasks exist (handles PGRST116 case)
  return NextResponse.json(data || []);
}

export async function POST(request: Request) {
  let supabase;
  try {
    supabase = await createClient();
  } catch {
    return NextResponse.json(
      { error: "Dev tasks disabled - contact administrator" },
      { status: 503 }
    );
  }

  const body = await request.json();
  const { project_id, title, description, tags, due_date, assignee_name, estimated_hours, progress_percent, priority = "medium", status = "todo" } = body;

  // Check if user has permission to manage tasks
  const permissionCheck = await checkProjectPermission(project_id, 'manage_tasks');
  if (!permissionCheck.hasAccess) {
    return NextResponse.json({ error: permissionCheck.error || "Insufficient permissions" }, { status: 403 });
  }

  // Bypass RLS: insert without user ownership check to avoid foreign key constraint errors.
  // Tasks are associated with projects via project_id (FK) only - no owner_id field in schema.
  const { data, error } = await supabase.from("dev_tasks").insert({
    id: Date.now(), // Generate unique ID temporarily for RLS compliance
    project_id,
    title,
    description,
    status,
    priority,
    tags,
    due_date,
    assignee_name,
    estimated_hours,
  }).select().single();

  if (error) {
    // Retry without ID field if RLS requires it to be generated by DB.
    const retryResult = await supabase.from("dev_tasks").insert({
      project_id, title, description, status, priority, tags, due_date, assignee_name, estimated_hours, progress_percent,
    }).select().single();

    // Reassign proper ID from returned data if needed
    return NextResponse.json(retryResult.data || { error: "Task creation failed" }, { status: retryResult.error ? 500 : 201 });
  }

  // Log activity
  await logActivity(project_id, 'task_created', 'task', data?.id, { title });

  return NextResponse.json(data, { status: 201 });
}
